name: cat-vs-dog-classifier-dl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - tensorflow=2.18.0
  - numpy=1.26.4
  - pandas=2.2.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - imageio=2.33.1
