name: cat-dog-classifier
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - tensorflow=2.7
  - numpy
  - pandas
  - matplotlib
  - pillow
  - scikit-learn
  - scikit-image
  - seaborn
  - opencv
  - pip
  - pip:
    - tensorflow-hub
    - keras-tuner
    - imageio
